name: Test downstream projects

on:
  push:
    branches: ["main"]
  pull_request:

concurrency:
  group: downstream-${{ github.ref }}
  cancel-in-progress: true

jobs:
  tests:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    strategy:
      matrix:
        python-version: ["3.9"]
      fail-fast: false
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Base Setup
        uses: jupyterlab/maintainer-tools/.github/actions/base-setup@v1

      - name: Test IPykernel
        uses: jupyterlab/maintainer-tools/.github/actions/downstream-test@v1
        with:
          package_name: ipykernel
          package_spec: "pyqt5 ipykernel[test]"

      - name: Test NBClient
        uses: jupyterlab/maintainer-tools/.github/actions/downstream-test@v1
        with:
          package_name: nbclient
          env_values: IPYKERNEL_CELL_NAME=\<IPY-INPUT\>

      # Note: Currently fails
      # - name: Test QtConsole
      #   uses: jupyterlab/maintainer-tools/.github/actions/downstream-test@v1
      #   with:
      #     package_name: qtconsole

      - name: Test nbconvert
        uses: jupyterlab/maintainer-tools/.github/actions/downstream-test@v1
        with:
          package_name: nbconvert

      - name: Test jupyter_server
        uses: jupyterlab/maintainer-tools/.github/actions/downstream-test@v1
        with:
          package_name: jupyter_server

      # Test using jupyter_kernel_test

      - name: Setup conda ${{ matrix.python-version }}
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          activate-environment: jupyter_kernel_test
          miniforge-variant: Mambaforge
          python-version: ${{ matrix.python-version }}

      - name: Test jupyter_kernel_test
        shell: bash -l {0}
        run: |
          git clone https://github.com/jupyter/jupyter_kernel_test.git
          cd jupyter_kernel_test
          conda env update --name jupyter_kernel_test --file environment.yml
          conda install -c conda-forge xeus-cling
          pip install -e ".[test]"
          python -m unittest -v
